### ISSUE TITLE
How to change String on the main screen in game home

### ISSUE THREAD

**Issue by chirag-deshwal** [guiquintelas/blue-box#1]
[https://drive.google.com/open?id=1V2CjtNghjiUCJmcNLN_8dyESmpsai3re](url)

View the for best You know that

**Comment by guiquintelas** [comment]
In the MenuState.java file, lines 244 and 251

https://github.com/guiquintelas/blue-box/blob/9575f357252b8ef943071aee08eda4a14267b17c/app/src/main/java/self/frota/guilherme/game/states/MenuState.java#L244-L251
